

export const FETCH_DATA = 'FETCH_DATA';

export const FETCH_DATA_FAILED = 'FETCH_DATA_FAILED'

export const FETCH_SUCCEED = 'FETCH_SUCCEED'

export const FETCH_DATA_CONCAT = 'FETCH_DATA_CONCAT'

export const FETCH_CONCAT_SUCCEED = 'FETCH_CONCAT_SUCCEED'

export const FETCH_CONCATDATA_FAILED = 'FETCH_CONCATDATA_FAILED'
